# Use root/example as user/password credentials
version: '3.1'

services:

  database:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose: 
      - "3306"
    ports: 
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: adminSA

  backend:
    build: .
    expose: 
      - "3000"
    ports: 
      - 3000:3000
    depends_on:
      - database